### ISSUE TITLE
Purpose statements

### ISSUE THREAD

**Issue by ifteda** [conorpaschenko/A1Part2#18]
The purpose statement for queue_push() should be updated to reflect the removal of capacity.

The purpose statement for equals() should also be changed, as hash codes themselves do not determine equality.

**Comment by hurda21** [comment]
Kinda unrelated, but on a similar note (syntax) -
Would you guys mind deciding on a consistent naming convention for your functions? Some have under_scored naming while others have camelCase. Either is fine as long as it's consistent.

Not sure if styling will play a role in our grade, but just in case (also helps with readability).

**Comment by frankkulak** [comment]
Going off of what @hurda21  said, I also think the following names can be simplified:
- `queue_empty()` should be `is_empty()`
- `queue_push()` should be `push()`
- `queue_pop()` should be `pop()`

The prefix `queue` in each of these methods is redundant since we already know the data structure we are working with when calling them. Additionally, `is_empty()` helps with readability, since it returns a boolean.

**Comment by james-herbstritt** [comment]
Done
