### ISSUE TITLE
Do not delete Queue contents in tests

### ISSUE THREAD

**Issue by ifteda** [conorpaschenko/A1Part2#19]
In test-queue.cpp, could you remove lines that delete the contents of a queue (e.g., lines 50-51, 69-70, etc.)? We ask this because, in our implementation, deleting the queue also deletes its elements, so leaving those additional lines in the tests means attempting to delete the already-deleted elements.
We agree that the objects should be copied, but we have no way of actually doing so reliably, given that there is no clone or copy method in object (and adding one now seems a bit late, as each team depends on one other).

EDIT: Additionally, we ask that you refrain from adding the same object to different queues, or to the same queue more than once. We understand that this is a feature that would be nice to have, but, again, there is no reliable way to implement it without clone(), as mentioned above.

**Comment by kyleacmooney** [comment]
@ifteda that suggestion would create a conflict for my team: Another student and I had a conversation with Vitek about the copying of Objects stored in containers (such as list, array, queue, etc. type classes), and he strongly advised that containers should only store the pointers (to Objects) that we are given, rather than copies of the Objects themselves.  The clients therefore are responsible for the memory allocation and deallocation of the Objects pointed to the pointers they are storing in these containers.  

Also: You point out that we do not have available copy methods for all Objects---this is true given the object.h APIs that the class seems to be settling on---but you are still deleting the objects pointed to by your queue's stored pointers upon a queue's deletion?  It would make sense to me to do this if we actually we able to (and if we were supposed to) store copies, but we aren't.  Your suggestion would conflict with our implementation and Vitek's suggestion for how containers should work.

**Comment by ifteda** [comment]
Ah, I understand. This should only be a small change on our part, so we will update our implementation accordingly. Thanks!
