### ISSUE TITLE
Change type of front and back in queue.h

### ISSUE THREAD

**Issue by frankkulak** [conorpaschenko/A1Part2#7]
The `front` and `back` fields are of type `unsigned int`, yet the size of the queue is a `size_t`. A `size_t` is an `unsigned long`, so clearly there's some mismatch here. Please update `front` and `back` to also be `size_t`.

**Comment by kyleacmooney** [comment]
Actually, we made an issue for this (Issue #6: **Remaining implementation + fields**) but recommended an int type for all of these fields---or at the very least for back---since making back an unsigned integer would restrict our implementation.  One of the instructor's responses on piazza mentioned this would be a problem in API design:

"When providing a specification, your goal is to put all of the information needed by someone to implement it but you should avoid putting details that will constrain that implementation."
(https://piazza.com/class/k51bluky59n2jr?cid=291)

We do not need to specify *private* field types (or private "helper" method signatures) in an API.  In our Issue request we therefore requested that the owners of this repo *remove* the fields altogether, or at the very least change the integers to signed.

**Comment by james-herbstritt** [comment]
Fields removed
